version: "3"

services:

  node_server:
    image: node:latest
    ports: 
      - "8080:8080"
    volumes: 
      - .:/apps/timvel-server
    restart: always
    working_dir: /apps/timvel-server
    networks:
      backend:
        aliases:
          - main_node
    env_file: 
      - ./env.list
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: ["npm","run","start"]
    
networks:
  backend:
